version: '3'

services:

  postgres:
    container_name:  postgres-db-chat_app
    image:           postgres:11
    ports:
      - 5432:5432 # Bind host port 5432 to PostgreSQL port 5432
    volumes:
      - ../pgdb:/var/lib/postgresql/data
#      - ../_backup/backup_defaultdb_06-Jan-2020.pgsql:/docker-entrypoint-initdb.d/restore.sql
    env_file: ../.env
    environment:
      - LC_ALL=C.UTF-8

#  redis:
#    image: redis:5
#    restart: "on-failure"
#    container_name: redis
#    ports:
#      - 6379:6379
#    volumes:
#      - ../redisdb:/var/lib/redis
  app:
    build:
      context: .
      dockerfile: ../Dockerfile
    env_file:
      - .env
    ports:
      - "8000:8000"
    restart: always
    links:
      - postgres
    depends_on:
      - "postgres"
    volumes:
      - ../:/app
    command: bash -c " source /venv/bin/activate && python /app/manage.py makemigrations --noinput && python /app/manage.py makemigrations --merge && python /app/manage.py migrate && python /app/manage.py runserver 0.0.0.0:8000"
