# Generated by Django 3.2.12 on 2022-03-07 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_user', '0002_profile_useractivation_useraudience'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='extra',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
