# Generated by Django 3.2.12 on 2022-03-09 07:02

import base_user.tools.common
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_user', '0003_alter_myuser_extra'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='profile_picture',
            field=models.FileField(blank=True, default='client/assets/user_icon.svg', upload_to=base_user.tools.common.get_user_profile_photo_file_name),
        ),
    ]
