# Generated by Django 3.2.12 on 2022-03-22 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_user', '0004_alter_myuser_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='facebook_account_url',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='instagram_account_url',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='twitter_account_url',
            field=models.URLField(null=True),
        ),
    ]
