# Generated by Django 3.2.12 on 2022-04-06 09:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_user', '0007_alter_profile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='contacts',
            field=models.ManyToManyField(blank=True, related_name='_base_user_myuser_contacts_+', to=settings.AUTH_USER_MODEL),
        ),
    ]
