# Generated by Django 3.2.12 on 2022-02-14 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_setting'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='client_prefix',
            field=models.CharField(blank=True, default='CTA', max_length=3),
        ),
    ]
