# Generated by Django 3.2.12 on 2022-03-09 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_message_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='is_group_update_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='setting',
            name='is_multi_user_group_creation_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='setting',
            name='is_user_social_accounts_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='setting',
            name='is_user_status_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
