# Generated by Django 3.2.12 on 2022-04-04 18:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0009_auto_20220309_1148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatgroup',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='group_users', to=settings.AUTH_USER_MODEL),
        ),
    ]
