# Generated by Django 3.2.12 on 2022-04-06 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_chatgroup_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatgroup',
            name='is_contact',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
